version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    environment:
      - SERVER_NAME=backend
    networks:
      - app_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_JSON=/swagger/openapi.json  # 指向 Flask OpenAPI 文檔
    ports:
      - "8090:8080"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./swagger:/swagger

  db:
    build:
      context: ./database
    container_name: database
    restart: always
    volumes:
      - ./sql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SOGO
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
